package com.adkhambek.treant.idea

import com.intellij.lang.documentation.AbstractDocumentationProvider
import com.intellij.psi.PsiElement
import org.jetbrains.kotlin.analysis.api.analyze
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name
import org.jetbrains.kotlin.psi.KtClassOrObject
import org.jetbrains.kotlin.psi.KtObjectDeclaration
import org.jetbrains.kotlin.psi.KtProperty

class TreantDocumentationProvider : AbstractDocumentationProvider() {

    private val treantAnnotations = listOf(
        "Slf4j", "Log", "CommonsLog", "Log4j", "Log4j2", "XSlf4j",
    ).map { name ->
        name to ClassId(FqName("com.adkhambek.treant"), Name.identifier(name))
    }

    override fun generateDoc(element: PsiElement, originalElement: PsiElement?): String? {
        val property = element as? KtProperty ?: return null
        val propName = property.name ?: return null
        if (propName != "log") return null

        val companion = property.parent?.parent as? KtObjectDeclaration ?: return null
        if (!companion.isCompanion()) return null
        val ownerClass = companion.parent?.parent as? KtClassOrObject ?: return null
        val ownerFqName = ownerClass.fqName?.asString() ?: return null

        val annotation = findTreantAnnotation(ownerClass) ?: return null

        return when (annotation) {
            "Slf4j" -> buildString {
                append("<div class='definition'><pre>")
                append("private val log: Logger = LoggerFactory.getLogger($ownerFqName::class.java)")
                append("</pre></div>")
                append("<div class='content'>")
                append("<p><i>Generated by the Treant compiler plugin (@Slf4j)</i></p>")
                append("<p>SLF4J Logger instance for the enclosing class.</p>")
                append("</div>")
            }
            "Log" -> buildString {
                append("<div class='definition'><pre>")
                append("private val log: Logger = java.util.logging.Logger.getLogger(\"$ownerFqName\")")
                append("</pre></div>")
                append("<div class='content'>")
                append("<p><i>Generated by the Treant compiler plugin (@Log)</i></p>")
                append("<p>java.util.logging.Logger instance for the enclosing class.</p>")
                append("</div>")
            }
            "CommonsLog" -> buildString {
                append("<div class='definition'><pre>")
                append("private val log: Log = LogFactory.getLog($ownerFqName::class.java)")
                append("</pre></div>")
                append("<div class='content'>")
                append("<p><i>Generated by the Treant compiler plugin (@CommonsLog)</i></p>")
                append("<p>Apache Commons Logging instance for the enclosing class.</p>")
                append("</div>")
            }
            "Log4j" -> buildString {
                append("<div class='definition'><pre>")
                append("private val log: Logger = Logger.getLogger($ownerFqName::class.java)")
                append("</pre></div>")
                append("<div class='content'>")
                append("<p><i>Generated by the Treant compiler plugin (@Log4j)</i></p>")
                append("<p>Log4j 1.x Logger instance for the enclosing class.</p>")
                append("</div>")
            }
            "Log4j2" -> buildString {
                append("<div class='definition'><pre>")
                append("private val log: Logger = LogManager.getLogger($ownerFqName::class.java)")
                append("</pre></div>")
                append("<div class='content'>")
                append("<p><i>Generated by the Treant compiler plugin (@Log4j2)</i></p>")
                append("<p>Log4j 2.x Logger instance for the enclosing class.</p>")
                append("</div>")
            }
            "XSlf4j" -> buildString {
                append("<div class='definition'><pre>")
                append("private val log: XLogger = XLoggerFactory.getXLogger($ownerFqName::class.java)")
                append("</pre></div>")
                append("<div class='content'>")
                append("<p><i>Generated by the Treant compiler plugin (@XSlf4j)</i></p>")
                append("<p>SLF4J extended XLogger instance for the enclosing class.</p>")
                append("</div>")
            }
            else -> null
        }
    }

    private fun findTreantAnnotation(classOrObject: KtClassOrObject): String? {
        analyze(classOrObject) {
            val symbol = classOrObject.symbol
            for ((name, classId) in treantAnnotations) {
                if (symbol.annotations.any { it.classId == classId }) return name
            }
        }
        return null
    }
}
