package com.adkhambek.treant.idea

import com.intellij.codeInspection.LocalInspectionTool
import com.intellij.codeInspection.ProblemsHolder
import com.intellij.psi.PsiElementVisitor
import org.jetbrains.kotlin.psi.KtClassOrObject
import org.jetbrains.kotlin.psi.KtObjectDeclaration
import org.jetbrains.kotlin.psi.KtProperty
import org.jetbrains.kotlin.psi.KtVisitorVoid

class TreantManualLoggerInspection : LocalInspectionTool() {

    override fun buildVisitor(holder: ProblemsHolder, isOnTheFly: Boolean): PsiElementVisitor {
        return object : KtVisitorVoid() {
            override fun visitProperty(property: KtProperty) {
                val name = property.name ?: return
                if (name != "log") return

                val companion = property.parent?.parent as? KtObjectDeclaration ?: return
                if (!companion.isCompanion()) return
                val ownerClass = companion.parent?.parent as? KtClassOrObject ?: return

                val annotation = TreantAnnotations.findAnnotation(ownerClass) ?: return

                holder.registerProblem(
                    property.nameIdentifier ?: property,
                    "'log' is automatically generated by the Treant compiler plugin for @$annotation classes. This manual definition will conflict with the generated log.",
                )
            }
        }
    }
}
