[versions]
kotlin = "2.4.10"
treant = "1.0.0"
kctfork = "0.13.0"
junit5 = "6.1.2"
maven-publish = "0.37.0"

[libraries]
treant-annotations = { module = "com.adkhambek.treant:treant-annotations", version.ref = "treant" }
kctfork-core = { module = "dev.zacsweers.kctfork:core", version.ref = "kctfork" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
maven-publish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "maven-publish" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
treant = { id = "com.adkhambek.treant", version.ref = "treant" }
